helloMessage: Hello World!

server:
  type: default
  maxThreads: 32
  applicationConnectors:
    - type: http
      port: 8080
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      acceptorThreads: 2
      selectorThreads: 2
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 32KiB
  requestLog:
    appenders:
      - type: console

logging:
  level: INFO
  loggers:
    "de.jeha.demo": DEBUG
  appenders:
   - type: console
#    - type: logstash-event-log-tcp
#      destination: logstash:4560
#      applicationName: dropwizard-demo
#      applicationVersion: 0.1-SNAPSHOT
#    - type: console-json
#      appendLineSeparator: true
