helloMessage: Hello World!

server:
  type: default
  maxThreads: 32
  applicationConnectors:
    - type: http
      port: 8080
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      acceptorThreads: 2
      selectorThreads: 2
  adminConnectors:
    - type: http
      port: 8081
  gzip:
    enabled: true
    bufferSize: 32KiB
  requestLog:
    timeZone: UTC
    appenders:
      - type: console
#      - type: logstash-access-log-tcp
#        destination: logstash:4560
#        applicationName: dropwizard-demo
#        applicationVersion: 0.1-SNAPSHOT

logging:
  level: INFO
  loggers:
    "de.jeha.demo": DEBUG
  appenders:
    - type: logstash-event-log-tcp
      destination: logstash:4560
      applicationName: dropwizard-demo
      applicationVersion: 0.1-SNAPSHOT
#    - type: logstash
#      host: logging2.virtual
#      port: 514
#      tag: jns-test
#    - type: console-json
#      appendLineSeparator: true
    - type: console
#    - type: syslog
#      host: localhost
#      port: 514
#      facility: local7
